export const TRANSLATE = {
  RU: {
    buttonContent: 'Узнать больше',
    backToList: 'Назад к списку',
    mainPage: 'Главная страница',
    photographersList: 'Список фотографов',
    ourTeam: 'Наша команда',
    worklog: 'Ворклог',
    styleGuide: 'Стайл Гайд',
    authorOfTheDay: 'Фотограф дня',
    photographerWorks: ' - работы',
  },
  EN: {
    buttonContent: 'Learn more',
    backToList: 'Back to list',
    mainPage: 'Main Page',
    photographersList: 'List of photographers',
    ourTeam: 'Our team',
    worklog: 'Worklog',
    styleGuide: 'Style Guide',
    authorOfTheDay: 'Photographer of the day',
    photographerWorks: '\'s works',
  },
  BE: {
    buttonContent: 'Даведацца больш',
    backToList: 'Назад да спiсу',
    mainPage: 'Галоўная старонка',
    photographersList: 'Спіс фатографаў',
    ourTeam: 'Наша каманда',
    worklog: 'Ворклог',
    styleGuide: 'Стайл Гайд',
    authorOfTheDay: 'Фатограф дня',
    photographerWorks: ' - працы',
  }
};
